#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
targetpath=$3
UUID=$(cat /proc/sys/kernel/random/uuid)

# Check domain/path availability
sudo yunohost app checkurl "$domain$path" -a reverse_proxy
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

#Set the target path for upgrade
sudo yunohost app setting reverse_proxy targetpath -v "$targetpath"
#Set the UUID for this app
sudo yunohost app setting reverse_proxy uuid -v "$UUID"

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path/@g" ../conf/nginx.conf
sed -i "s@TARGETTOCHANGE@$targetpath/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf "/etc/nginx/conf.d/$domain.d/reverse_proxy_$UUID.conf"

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
