#!/bin/bash

domain=$(sudo yunohost app setting external_proxy domain)
path=$(sudo yunohost app setting external_proxy path)
targetpath=$(sudo yunohost app setting external_proxy targetpath)
UUID=$(sudo yunohost app setting external_proxy uuid)

sed -i "s@PATHTOCHANGE@$path/@g" ../conf/nginx.conf
sed -i "s@TARGETPATHTOCHANGE@$targetpath/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf "/etc/nginx/conf.d/$domain.d/reverse_proxy$UUID.conf"

sudo service nginx reload
sudo yunohost app ssowatconf